kind: pipeline
type: docker
name: default
steps:
    - name: test
      image: golang:1.10-alpine
      commands:
          - "go test"
    - name: build
      image: golang:1.10-alpine
      commands:
          - "go build -o ./myapp"
    - name: publish
      image: plugins/docker
      settings:
          repo: nothingrealm/drone
          tags: [ latest, 1.0, 1 ]
          username:
              from_secret: docker_username
          password:
              from_secret: docker_password
    - name: deliver
      image: sinlead/drone-kubectl
      settings:
          kubernetes_server:
              from_secret: kube_server
          kubernetes_cert:
              from_secret: kube_ca
          kubernetes_token:
              from_secret: kube_token
      commands:
          - kubectl apply -f service_and_deployment.yml
      when:
          event: [ push ]
trigger:
    branch:
        - master
    event:
        - push
