kind: pipeline
type: docker
name: default
steps:
    - name: test
      image: golang:1.10-alpine
      commands:
          - "go test"
    - name: build
      image: golang:1.10-alpine
      commands:
          - "go build -o ./myapp"
    - name: deliver
      image: sinlead/drone-kubectl
      settings:
          kubernetes_server:
              from_secret: kube_server
          kubernetes_cert:
              from_secret: kube_ca
          kubernetes_token:
              from_secret: kube_token
      when:
          event: [ push ]
trigger:
    branch:
        - master
    event:
        - push
