kind: pipeline
type: docker
name: default
steps:
    - name: test
      image: golang:1.10-alpine
      commands:
          - "go test"
    - name: build
      image: golang:1.10-alpine
      commands:
          - "go build -o ./myapp"
    - name: deliver
      image: vallard/drone-kube
      setting:
          template: service_and_deployment.yml
          server: 192.168.39.86:8443
      environment:
          KUBE_SERVER: 192.168.39.86:8443
          KUBE_TOKEN:
              from_secret: KUBE_TOKEN
          KUBE_CA:
              from_secret: KUBE_CA
      when:
          event: [ push ]
trigger:
    branch:
        - master
    event:
        - push
