apiVersion: v1
kind: Service
metadata:
    name: drone-svc
spec:
    type: NodePort
    selcetor:
        app: drone
    ports:
        - protocol: TCP
          port: 80
          targetPort: 8080
          nodePort: 32000
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: drone-dep
spec:
    replicas: 2
    selector:
        matchLabel:
            app: drone
    template:
        metadata:
            labels:
                app: drone
        containers:
            - name: server
              image: "nothingrealm/drone"
              resources:
                  requests:
                      cpu: 10m
                      memory: 128Mi
